# Generated by Django 5.1.2 on 2024-10-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('marca', models.CharField(max_length=10)),
                ('color_vehiculo', models.CharField(choices=[('1', 'Blanco'), ('2', 'Negro'), ('3', 'Rojo'), ('4', 'Azul'), ('5', 'Amarillo'), ('6', 'Gris')], max_length=1, verbose_name='color')),
                ('modelo', models.IntegerField()),
            ],
        ),
    ]
